### ISSUE TITLE
Have a separate folder for each component type under integrations

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#100]
**Is your feature request related to a problem? Please describe.**
As a user, I'm familiar with the convention at haystack repository and having the same convention here would make it easy for me to navigate.

**Describe the solution you'd like**
Create a `/generators` folder under `cohere_haystack` integration folder. 
The same can apply to `jina_haystack` and `unstructured`. This way, we can be more open to new components coming from the same providers

**Describe alternatives you've considered**
We can leave it as it is.

**Additional context**
N/A

```[tasklist]
### Tasks
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/195
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/196
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/197
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/198
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/199
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/200
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/201
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/202
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/203
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/210
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/209
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/208
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/207
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/206
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/205
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/204
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/213
```

**Comment by masci** [comment]
We're going to uniform the import path of all the integrations under the namespace `haystack_integrations.*`.

For example, this means that a document store `FooDocumentStore` shipped with the integration `baz-haystack` will be imported like this:

```py
from haystack_integrations.document_stores.baz import FooDocumentStore
```

Similarly, a generator `AwesomeGenerator` shipped with the integration `foo-haystack` will be imported like this:

```py
from haystack_integrations.components.generators.foo import AwesomeGenerator
```
