### ISSUE TITLE
Migration from vertex_ai.preview to vertex_ai.generative_model

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#1018]
## Summary and motivation

Current integration of VertexAIGemini uses `vertex_ai.preview` package which has some experimental features. We should migrate to a more stable `vertetx_ai.generative_model` package. 

## Checklist

```[tasklist]
### Tasks
- [ ] The changes are merged in the `main` branch (Code + Docstrings)
- [ ] New package version declares the breaking change
- [ ] The package has been released on PyPI
- [ ] Docs at https://docs.haystack.deepset.ai/ were updated
- [ ] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
- [ ] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (if needed)
- [ ] Tutorials on https://github.com/deepset-ai/haystack-tutorials were updated (if needed)
- [ ] Articles on https://github.com/deepset-ai/haystack-home/tree/main/content were updated (if needed)
```

**Comment by julian-risch** [comment]
Look out for breaks of the serialization
