### ISSUE TITLE
Remove unsupported models from Gemini integration

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#1024]
### Summary and motivation
According to [google release notes](https://ai.google.dev/gemini-api/docs/changelog), the `gemini-pro-vision` and `gemini-ultra` model are unsupported. We should update our Gemini integration to support latest models like`gemini-1.5-flash`.

```[tasklist]
### Tasks
- [x] The changes are merged in the `main` branch (Code + Docstrings)
- [x] New package version declares the breaking change
- [x] The package has been released on PyPI
- [x] Docs at https://docs.haystack.deepset.ai/ were updated
- [x] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
- [x] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (if needed)
- [x] Tutorials on https://github.com/deepset-ai/haystack-tutorials were updated (if needed)
- [x] Articles on https://github.com/deepset-ai/haystack-home/tree/main/content were updated (if needed)
```
