### ISSUE TITLE
Ollama: use the python library instead of the API

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#1062]
## Summary and motivation
This makes things easier and should reduce maintenance efforts.
Also, as reported by a community member, integrating tools becomes easier.

## Checklist

```[tasklist]
### Tasks
- [x] The changes are merged in the `main` branch (Code + Docstrings)
- [x] New package version declares the breaking change
- [x] The package has been released on PyPI
- [x] Docs at https://docs.haystack.deepset.ai/ were updated
- [x] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
- [x] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (if needed)
- [x] Tutorials on https://github.com/deepset-ai/haystack-tutorials were updated (if needed)
- [x] Articles on https://github.com/deepset-ai/haystack-home/tree/main/content were updated (if needed)
```

**Comment by anakin87** [comment]
done
