### ISSUE TITLE
Add OptimumEmbedder

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#137]
**Is your feature request related to a problem? Please describe.**
Huggin Face's Optimum library provides faster inference through ONNX and TensorRT. This can be used to create blazing fast embedding components. The concepts used in Optimum also play well with some of the concepts that we have in Haystack. For example:

Loading non-ONNX checkpoints requires a conversion step, this takes some time. We can do that step in our warmup function (https://huggingface.co/docs/optimum/onnxruntime/usage_guides/models#loading-a-vanilla-transformers-model).

**Describe the solution you'd like**
- fast embedders based on Optimum
- apply other tricks such as sorting by sequence length and dynamic padding to bring down inference time (see https://github.com/UKPLab/sentence-transformers/blob/c006921e9e9977bc107b05676266b581091688a2/sentence_transformers/SentenceTransformer.py#L179)

**Describe alternatives you've considered**
- Not having a fast embedder component
- https://github.com/qdrant/fastembed > supported models are limited

**Additional context**
https://colab.research.google.com/drive/10UAtpz26Gv2LtamT8j33LmI5UFQFwF4T?usp=sharing
https://github.com/huggingface/optimum-benchmark/tree/main/examples/fast-mteb

```[tasklist]
### Tasks
- [x] The code is documented with docstrings and was merged in the `main` branch
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/742
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media
```

**Comment by shadeMe** [comment]
Reopening as the docs are still missing. Nor have we announced this on social media (to the best of my knowledge).

**Comment by dfokina** [comment]
The docs are live: https://docs.haystack.deepset.ai/docs/optimumtextembedder, https://docs.haystack.deepset.ai/docs/optimumdocumentembedder

I believe only the social media announcement is left
