### ISSUE TITLE
Add AnthropicGenerator

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#139]
**Is your feature request related to a problem? Please describe.**
Anthropic models are widely used. We should support them in 2.0.

**Describe the solution you'd like**
Generator similar to the Anthropic support in 1.x

```[tasklist]
### Tasks
- [ ] The code is documented with docstrings and was merged in the `main` branch
- [ ] Docs are published at https://docs.haystack.deepset.ai/
- [ ] There is a Github workflow running the tests for the integration nightly and at every PR
- [ ] A label named like `integration:<your integration name>` has been added to this repo
- [ ] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [ ] The package has been released on PyPI
- [ ] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [ ] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [ ] There is an example available to demonstrate the feature
- [ ] The feature was announced through social media
```

**Comment by sahusiddharth** [comment]
@mathislucka can you provide me with some kind of starting point, about the minimal interface that is required for this?

**Comment by anakin87** [comment]
@sahusiddharth I can have a look later today and point to the right resources/examples.

It is necessary that you have access to Anthropic to do local experiments. Do you have access to Anthropic?

**Comment by sahusiddharth** [comment]
Hi @anakin87, currently I don't have access. Would you mind sharing an API key for experimentation in the meantime? Thanks!

**Comment by anakin87** [comment]
Anthropic is only available for some countries, so I can't share with you a usable API key.
I would advise you to focus on some other contribution. :heart_decoration:

**Comment by vblagoje** [comment]
The issue was a bit prematurely closed. The only two remaining tasks (as of 18.3.24) are publishing the docs and social media announcement
