### ISSUE TITLE
Add SagemakerGenerator

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#140]
**Is your feature request related to a problem? Please describe.**
Sagemaker is widely used for LLM inference in production use cases. We should support Sagemaker in 2.0.

**Describe the solution you'd like**
Generator similar to the Sagemaker support in 1.x

```[tasklist]
### Tasks
- [x] Implementation: https://github.com/deepset-ai/haystack-core-integrations/issues/275
- [ ] Docs are published at https://docs.haystack.deepset.ai/ https://github.com/deepset-ai/haystack-core-integrations/issues/296
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [ ] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations: https://github.com/deepset-ai/haystack-core-integrations/issues/292
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README: https://github.com/deepset-ai/haystack-core-integrations/issues/290
- [ ] There is an example available to demonstrate the feature: https://colab.research.google.com/drive/1S3QO4OWx3oK58XVAVo0SissekA6NViaC#scrollTo=EX5oCws-etEH
- [ ] The feature was announced through social media
```
