### ISSUE TITLE
[Amazon Bedrock] Add AmazonBedrockChatGenerator

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-core-integrations#180]
In addition to the recently merged AmazonBedrockGenerator https://github.com/deepset-ai/haystack-core-integrations/pull/153, we need a AmazonBedrockChatGenerator supporting ChatMessages as format.

```[tasklist]
### Tasks
- [x] The change is documented with docstrings and was merged in the `main` branch
- [x] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
- [ ] Docs at https://docs.haystack.deepset.ai/ were updated
- [ ] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (if needed)
- [ ] New package version declares the breaking change and package has been released on PyPI
```
