### ISSUE TITLE
[Amazon Bedrock] Add AmazonBedrockEmbedder

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-core-integrations#181]
In addition to the recently merged AmazonBedrockGenerator https://github.com/deepset-ai/haystack-core-integrations/pull/153, we need an AmazonBedrockEmbedder for the embedding models.
```[tasklist]
### Tasks
- [x] The code is documented with docstrings and was merged in the `main` branch
- [x] The package has been released on PyPI
- [x] Docs are published at https://docs.haystack.deepset.ai/ (in review...)
- [x] integration tile update - https://github.com/deepset-ai/haystack-integrations (in review...)
```

**Comment by dfokina** [comment]
@anakin87 The docs are published: https://docs.haystack.deepset.ai/v2.0/docs/amazonbedrockdocumentembedder
https://docs.haystack.deepset.ai/v2.0/docs/amazonbedrocktextembedder
