### ISSUE TITLE
opensearch: mount integration under haystack_integrations.*

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#208]
## Checklist

- [x] Update the structure, the code, and examples on haystack-core-integrations https://github.com/deepset-ai/haystack-core-integrations/pull/212
- [x] Update the integration tile on https://github.com/deepset-ai/haystack-integrations https://github.com/deepset-ai/haystack-integrations/pull/133
- [x] Update the docs at https://docs.haystack.deepset.ai/
- [x] Update the notebooks on https://github.com/deepset-ai/haystack-cookbook (if needed)
```[tasklist]
### Tasks
- [x] Update artici
```

**Comment by TuanaCelik** [comment]
I've updated the cookbook and ticked it off
