### ISSUE TITLE
Rename `model_name` and `model_name_or_path` parameters as `model` in all integrations

### ISSUE THREAD

**Issue by ZanSara** [deepset-ai/haystack-core-integrations#227]
Related to https://github.com/deepset-ai/haystack/issues/6534

### Is your feature request related to a problem? Please describe.
As a user, I'd like to have a similar interface for each Generator (possibly for all components accepting a model name) to pass the model name

### Describe the solution you'd like
We have discussed that parameters should be named as model but the most important point is to have consistency.

### TODOs:
   - [x] Amazon Bedrock: https://github.com/deepset-ai/haystack-core-integrations/pull/220
   - [x] Cohere: https://github.com/deepset-ai/haystack-core-integrations/pull/222
   - [x] GoogleAI: already correct
   - [x] Google Vertex: already correct
   - [x] Gradient: https://github.com/deepset-ai/haystack-core-integrations/pull/228
   - [x] Instructor: https://github.com/deepset-ai/haystack-core-integrations/pull/229
   - [x] Jina:https://github.com/deepset-ai/haystack-core-integrations/pull/230
   - [x] Llama.cpp: https://github.com/deepset-ai/haystack-core-integrations/pull/243
   - [x] Ollama: already correct
   - [x] Review all model cards & docs
   - [x] Review tutorials: 
     - https://github.com/deepset-ai/haystack-tutorials/pull/270 
   - [x] Review cookbook
   - [x] Review articles: 
     - https://github.com/deepset-ai/haystack-home/pull/289
