### ISSUE TITLE
Add support for AWS textract

### ISSUE THREAD

**Issue by MarkDirksen** [deepset-ai/haystack-core-integrations#2391]
Hi,

I was wondering if there is any interest in adding support for AWS textract for extracting text / tables ? I noticed there is already an option for a similar offering from Azure (AzureConverter). I mainly use AWS and it would be convenient to use Textract instead.

If there is interest in doing so I might be able to spend some time on it in the near future. In that case I'll have some questions on the details.

Thanks!

**Comment by bogdankostic** [comment]
### Tasks
- [x] The code is documented with docstrings and was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A new label named like `integration:<your integration name>` has been added to the list of labels for this [repository](https://github.com/deepset-ai/haystack-core-integrations/labels)
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile with a usage example has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [ ] The feature was announced through social media

**Comment by kacperlukawski** [comment]
Posts will go live tomorrow
