### ISSUE TITLE
Generate API docs for integrations

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#274]
Add a new Hatch command called `docs` that generates API docs for the integration.

Example PR: https://github.com/deepset-ai/haystack-core-integrations/pull/262

```[tasklist]
### Tasks
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/302
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/303
- [x] chroma
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/304
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/305
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/306
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/307
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/308
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/309
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/310
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/311
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/312
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/313
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/314
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/315
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/316
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/317
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/318
- [ ] https://github.com/deepset-ai/haystack-core-integrations/pull/266
```
