### ISSUE TITLE
Retriever Naming

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#319]
The receivers' names should refer to the **retrieval method** instead of the input type. This allows us to have specific retrievers for document stores (e.g. Chroma has `ChromaQueryRetriever` that refers to Chroma's `query` API, not Haystack's query input). 

**Things to pay attention**
Even if there's only one retrieval method that the document store supports, let's try to state the method in the retriever's name. e.g:
* `QdrantRetriever` ❌ 
* `QdrantEmbeddingRetriever` ✅

> ℹ️ It's quite hard to standardize the retriever naming across all databases. Let's be quite flexible here and not be afraid to introduce new retriever types.

### Some future retriever examples according to this convention
* Qdrant ([Qdrant Announcement about Splade](https://qdrant.tech/articles/sparse-vectors/#splade))
    * `QdrantSpladeRetriever` -> "Splade" is not totally clear for Haystack users but aligns with Qdrant quite well
    * `QdrantSparseRetriever` -> clearer for Haystack users but sounds like a quite general term, might create confusion if there are multiple sparse vector methods that cannot be supported with the same Retriever  
* `WeaviateHybridRetriever` -> This component might take `text` as input (not embeddings) and return retrieved documents by using [Weaviate's built-in hybrid search functionality](https://weaviate.io/developers/weaviate/search/hybrid) 

```[tasklist]
### Tasks
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/134
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/394
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/395
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/406
```

**Comment by sahusiddharth** [comment]
Hi @bilgeyucel, I'm working on this

- Issue #134 I have changed the retriever name to the proposed `QdrantEmbeddingRetriever` and the file retriever.py is already in retriever folder, is there anything else that needs to be done?
- `AstraRetriever` to `AstraEmbeddingRetriever` : done
- About the pinecone, can you tell me the `PineconeDenseRetriever` -> `PineconeEmbeddingRetriever` decision or should I just do it for now?

**Comment by anakin87** [comment]
Some material for thinking about Sparse Embedding Retrieval (to choose the right names):
- https://docs.pinecone.io/docs/hybrid-search
- https://qdrant.tech/articles/sparse-vectors/

**Comment by bilgeyucel** [comment]
Hi @sahusiddharth, we're still working on this issue so it's on hold at the moment. Feel free to pick another issue from ["Contributions Wanted"](https://github.com/deepset-ai/haystack-core-integrations/issues?q=is%3Aissue+is%3Aopen+label%3A%22contributions+wanted%21%22) list :)

**Comment by anakin87** [comment]
We decided for this **naming convention**:
Document Store + Technique + "Retriever"

Dense Embeddings Retriever → EmbeddingRetriever
Sparse Embedding Retriever → SparseEmbeddingRetriever

Examples:
- ElasticsearchBM25Retriever
- ElasticsearchEmbeddingRetriever
- QdrantEmbeddingRetriever
- QdrantSparseEmbeddingRetriever

**Comment by anakin87** [comment]
Done!

Docs will be improved according to the new Naming: #6976
