### ISSUE TITLE
Pgvector: adopt Secret for connection string

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#330]
We are introducing better management of secrets in Haystack (https://github.com/deepset-ai/haystack/pull/6855).

We should also take this approach for the Pgvector connection string, which can contain a password.

```[tasklist]
### Tasks
- [x] The changes are merged in the `main` branch (Code + Docstrings)
- [x] The package has been released on PyPI
- [x] Docs at https://docs.haystack.deepset.ai/ were updated
- [x] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
- [x] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (if needed)
- [x] Tutorials on https://github.com/deepset-ai/haystack-tutorials were updated (if needed)
- [x] Articles on https://github.com/deepset-ai/haystack-home/tree/main/content were updated (if needed)
```

**Comment by sahusiddharth** [comment]
Hello @anakin87, I was thinking something like this...

```python
class PgvectorDocumentStore:
    def __init__(
        self,
        *,
        user: str,
        password: Secret = Secret.from_env_var("PASSWORD"),
        host: str,
        port: int,
        db_name: str = "postgres"
        table_name: str = "haystack_documents",
        embedding_dimension: int = 768,
        vector_function: Literal["cosine_similarity", "inner_product", "l2_distance"] = "cosine_similarity",
        recreate_table: bool = False,
        search_strategy: Literal["exact_nearest_neighbor", "hnsw"] = "exact_nearest_neighbor",
        hnsw_recreate_index_if_exists: bool = False,
        hnsw_index_creation_kwargs: Optional[Dict[str, int]] = None,
        hnsw_ef_search: Optional[int] = None,
    ):
    self.connection_string = f"postgresql://{user}:{password.resolve_value()}@{host}:{port}/{db_name}"
```

Do you think I'm thinking in correct direction? and if yes it would be great if you could suggest some default values for `host`,  `port`, `user`.

**Comment by sahusiddharth** [comment]
@anakin87 no worries, I will look for something else
