### ISSUE TITLE
AstraRetriever -> AstraEmbeddingRetriever

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#394]
Part of #319

```[tasklist]
### Tasks
- [x] The changes are merged in the `main` branch (Code + Docstrings)
- [x] The package has been released on PyPI
- [x] Docs at https://docs.haystack.deepset.ai/ were updated
- [x] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
- [x] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (if needed)
- [x] Tutorials on https://github.com/deepset-ai/haystack-tutorials were updated (if needed)
- [x] Articles on https://github.com/deepset-ai/haystack-home/tree/main/content were updated (if needed)
```

```[tasklist]
### Tasks
```
