### ISSUE TITLE
Mistral Embedders and Generators

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-core-integrations#408]
## Summary and motivation

Creating this issue for https://github.com/deepset-ai/haystack/issues/6928

Mistral uses the same API as OpenAI and so far we've instructed people to use the OpenAIChatGenerator and OpenAITextEmbedder to make use of the Mistral API directly.

It would be good to have components that wrap these two which makes it nicer to use with Mistral: https://haystack.deepset.ai/integrations/mistral
## Detailed design

The components use the OpenAI embedders and generators. Currently mistral uses pretty much the identical API to OpenAI, but we can make changes when and if they move on to something else
 
## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.
```[tasklist]
### Tasks
- [ ] https://github.com/deepset-ai/haystack-core-integrations/pull/409
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media
- [x] Submit to Mistral Docs
```

**Comment by TuanaCelik** [comment]
@dfokina - I've prepared the docs on Notion.
Can I have a review on there please? I'm happy to publish when you see fit 👍
