### ISSUE TITLE
Google generators return `answers` instead of `replies`

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#600]
Generators in Google integrations return `answers` instead of `replies` in the output dictionary.

This makes it difficult to swap them with other Generators.
We should fix this inconsistency.

```[tasklist]
### Tasks
- [x] The changes are merged in the `main` branch (Code + Docstrings)
- [x] The package has been released on PyPI
- [x] Docs at https://docs.haystack.deepset.ai/ were updated
- [x] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated (in review)
- [x] Notebooks on https://github.com/deepset-ai/haystack-cookbook were updated (in review)
- [x] Tutorials on https://github.com/deepset-ai/haystack-tutorials were updated (if needed)
- [x] Articles on https://github.com/deepset-ai/haystack-home/tree/main/content were updated (in review)
```
