### ISSUE TITLE
CohereRanker

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#645]
Port the existing node https://github.com/deepset-ai/haystack/blob/v1.x/haystack/nodes/ranker/cohere.py to a component for 2.0

```[tasklist]
### Tasks
- [x] The code is documented with docstrings and was merged in the `main` branch
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/648
- [x] The package has been released on PyPI
- [x] Update the integration tile in https://github.com/deepset-ai/haystack-integrations
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media?
```

**Comment by anakin87** [comment]
```[tasklist]
### Tasks
- [ ] The code is documented with docstrings and was merged in the `main` branch
- [ ] Docs are published at https://docs.haystack.deepset.ai/
- [ ] The package has been released on PyPI
- [ ] Update the integration tile in https://github.com/deepset-ai/haystack-integrations
- [ ] There is an example available to demonstrate the feature
- [ ] The feature was announced through social media?
```

**Comment by anakin87** [comment]
New feature released -> https://pypi.org/project/cohere-haystack/0.6.0/

Integration tile: @AnushreeBannadabhavi would you like to open a PR to update [this file](https://github.com/deepset-ai/haystack-integrations/blob/main/integrations/cohere.md), showing this feature?

**Comment by AnushreeBannadabhavi** [comment]
Hi @anakin87!
Yes, I'd like to update the file. Thank you! I'll open a PR soon.

**Comment by AnushreeBannadabhavi** [comment]
Hi @anakin87!
Opened a [PR](https://github.com/deepset-ai/haystack-integrations/pull/217) for updating the integration tile.
