### ISSUE TITLE
Langfuse integration

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#646]
## Summary and motivation

Langfuse would be extremely helpful in monitoring and debugging Haystack pipelines, by visualising inputs and outputs for each component execution during a `pipeline.run()`.

## Detailed design

- The integration will use Haystack's tracing API
- A working MVP detailing the integration design is available here https://github.com/deepset-ai/haystack-core-integrations/tree/staging/integrations/langfuse

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.
```[tasklist]
### Tasks
- [x] The code is documented with docstrings and was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/709
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/710
```

**Comment by masci** [comment]
@deepset-ai/devrel FYI this will be scheduled for the upcoming sprint

**Comment by masci** [comment]
@vblagoje reopening as the task is not done, please make sure the tasklist is up to date!

**Comment by vblagoje** [comment]
Ok will do @masci

**Comment by vblagoje** [comment]
@dfokina @annthurium When the respective sub tasks are completed would you please mark them on this issue

**Comment by dfokina** [comment]
The docs are live: https://docs.haystack.deepset.ai/docs/langfuseconnector

**Comment by caubechankiu** [comment]
> The docs are live: https://docs.haystack.deepset.ai/docs/langfuseconnector

I followed the documentation but the result is
<img width="1364" alt="image" src="https://github.com/deepset-ai/haystack-core-integrations/assets/15911787/3d20c8ec-be08-479a-a64f-254ad5a4300a">

Here is my code
``` python
from haystack.dataclasses import ChatMessage
from haystack.components.generators.chat import OpenAIChatGenerator
from haystack.components.builders import DynamicChatPromptBuilder
from haystack import Pipeline
from haystack_integrations.components.connectors.langfuse import LangfuseConnector
from haystack import Pipeline
import os

os.environ["LANGFUSE_PUBLIC_KEY"] = "pk-lf-...."
os.environ["LANGFUSE_SECRET_KEY"] = "sk-lf-...."
os.environ["OPENAI_API_KEY"] = "sk-...."
os.environ["LANGFUSE_HOST"] = "https://cloud.langfuse.com"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["HAYSTACK_CONTENT_TRACING_ENABLED"] = "true"


pipe = Pipeline()
pipe.add_component("tracer", LangfuseConnector("Chat example"))
pipe.add_component("prompt_builder", DynamicChatPromptBuilder())
pipe.add_component("llm", OpenAIChatGenerator(model="gpt-3.5-turbo"))

pipe.connect("prompt_builder.prompt", "llm.messages")
messages = [
    ChatMessage.from_system("Always respond in German even if some input data is in other languages."),
    ChatMessage.from_user("Tell me about {{location}}"),
]

response = pipe.run(
    data={"prompt_builder": {"template_variables": {"location": "Berlin"}, "prompt_source": messages}}
)
print(response["llm"]["replies"][0])
print(response["tracer"]["trace_url"])
# ChatMessage(content='Berlin ist die Hauptstadt von Deutschland und zugleich eines der bekanntesten kulturellen Zentren Europas. Die Stadt hat eine faszinierende Geschichte, die bis in die Zeiten des Zweiten Weltkriegs und des Kalten Krieges zurückreicht. Heute ist Berlin für seine vielfältige Kunst- und Musikszene, seine historischen Stätten wie das Brandenburger Tor und die Berliner Mauer sowie seine lebendige Street-Food-Kultur bekannt. Berlin ist auch für seine grünen Parks und Seen beliebt, die den Bewohnern und Besuchern Raum für Erholung bieten.', role=<ChatRole.ASSISTANT: 'assistant'>, name=None, meta={'model': 'gpt-3.5-turbo-0125', 'index': 0, 'finish_reason': 'stop', 'usage': {'completion_tokens': 137, 'prompt_tokens': 29, 'total_tokens': 166}})
# https://cloud.langfuse.com/trace/YOUR_UNIQUE_IDENTIFYING_STRING

```

**Comment by vblagoje** [comment]
Hey @caubechankiu due to python class loading mechanism you need to import os first, set env values and then import everything else. Then it'll work. Also select the nodes below chat example (right panel) as the root doesn't have input only haystack.pipeline.run node and below. See below:

<img width="1114" alt="Screenshot 2024-05-04 at 13 30 53" src="https://github.com/deepset-ai/haystack-core-integrations/assets/458335/f7203660-49c9-42cb-b8b9-40d00d54f0d9">

And let us know if adjusting these worked. Here is my pip install on fresh virtual env:
```
pip install git+https://github.com/deepset-ai/haystack.git langfuse-haystack
```

**Comment by caubechankiu** [comment]
> Hey @caubechankiu due to python class loading mechanism you need to import os first, set env values and then import everything else. Then it'll work. Also select the nodes below chat example (right panel) as the root doesn't have input only haystack.pipeline.run node and below. See below:
> 
> <img alt="Screenshot 2024-05-04 at 13 30 53" width="1114" src="https://private-user-images.githubusercontent.com/458335/327944851-f7203660-49c9-42cb-b8b9-40d00d54f0d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjIyMjgsIm5iZiI6MTcxNDk2MTkyOCwicGF0aCI6Ii80NTgzMzUvMzI3OTQ0ODUxLWY3MjAzNjYwLTQ5YzktNDJjYi1iOGI5LTQwZDAwZDU0ZjBkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMjE4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjZlYTg5YWJhYTgyYzJhZmM5OTExOTliZDc0NjU5MzE4MjI3NTIwNDZjYjNkYmU3NjI5ZWNmYWUwZTU1ZTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZCAr8QK1iGIjRwIKRYWZX4sH9FNw-ccazQPxPyLgzAQ">
> And let us know if adjusting these worked. Here is my pip install on fresh virtual env:
> 
> ```
> pip install git+https://github.com/deepset-ai/haystack.git langfuse-haystack
> ```

Thank you! It worked.

**Comment by vblagoje** [comment]
@annthurium would you please close this issue after social media announcement

**Comment by annthurium** [comment]
yep!

**Comment by vblagoje** [comment]
Ok, I think we can finally close this one @annthurium @masci
