### ISSUE TITLE
Sparse Embeddings support: create docs/material

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#660]
FastEmbed SparseEmbedder introduced in #579
Support for sparse embeddings in Qdrant introduced in #659

```[tasklist]
### Tasks
- [ ] Create docs for FastEmbed SparseEmbedder
- [ ] Create docs for QdrantSparseEmbeddingRetriever
- [ ] Update FastEmbed integration tile at https://github.com/deepset-ai/haystack-integrations
- [ ] Prepare a cookbook showing the feature (might also include some form of Hybrid retrieval)
- [ ] The feature was announced through social media
```
