### ISSUE TITLE
Pgvector: support for keyword retrieval

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#724]
Currently, our Document Store only supports embedding retrieval.

It would be great to support the native full-text search capabilities of Postgres to perform keyword retrieval

Initial discussion and design: https://github.com/deepset-ai/haystack-core-integrations/pull/576#issuecomment-2014803348

```[tasklist]
### Tasks
- [x] The code is documented with docstrings and was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/ (in review...)
- [x] The package has been released on PyPI
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/726
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/727
- [ ] The feature was announced through social media?
```

**Comment by anakin87** [comment]
@jlonge4 feel free to contribute to #726/#727 if you want. :slightly_smiling_face:

**Comment by jlonge4** [comment]
@anakin87 definitely!
