### ISSUE TITLE
Add Supabase integration

### ISSUE THREAD

**Issue by mayankodin** [deepset-ai/haystack-core-integrations#73]
Hi , wondering if you will support supabse in near future

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.
```[tasklist]
### Tasks
- [ ] The code is documented with docstrings and was merged in the `main` branch https://github.com/deepset-ai/haystack-core-integrations/pull/263
- [ ] Docs are published at https://docs.haystack.deepset.ai/
- [ ] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [ ] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [ ] The package has been released on PyPI
- [ ] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [ ] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [ ] There is an example available to demonstrate the feature
- [ ] The feature was announced through social media
```

**Comment by mayankodin** [comment]
can you help me with minimu abstract emthods that are required for this , i can do PR

**Comment by masci** [comment]
A good starting point for creating a new document store from scratch is using this repo as a blueprint: https://github.com/deepset-ai/document-store

Also looking at existing document stores in this repo, like https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/chroma might help getting started.

**Comment by sahusiddharth** [comment]
Hi @mayankodin, 

When you said "supabase support" , do you mean [supabase ai and vectors ](https://supabase.com/docs/guides/ai)?

**Comment by masci** [comment]
We decided not to add a Supabase Core integration for now, contributors can still create an integration they own and maintain.
