### ISSUE TITLE
Deprecate use of legacy filters syntax in Document Stores integrations

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#829]
The legacy filters syntax from Haystack 1 must be deprecated in favour of the new one.

As of now if the legacy syntax is used we automatically convert it internally to the new one.
We should emit a deprecation warning instead.

After that is done we can also remove some utility classes in `testing` used to test Document Stores.

These are the integration that must be updated.
```[tasklist]
### Tasks
- [ ] deepset-ai/haystack-core-integrations#875
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/876
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/877
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/878
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/879
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/880
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/881
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/882
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/883
```
See also deepset-ai/haystack#7893

**Comment by julian-risch** [comment]
The legacy filter syntax was deprecated in the document store integrations.
Removal of utility classes in `testing` used to test Document Stores is tracked by a separate issue: https://github.com/deepset-ai/haystack/issues/8023
