### ISSUE TITLE
docs: clean up docstrings

### ISSUE THREAD

**Issue by agnieszka-m** [deepset-ai/haystack-core-integrations#935]
```[tasklist]
### Tasks
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/944
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/946
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/948
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/951
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/957
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/959
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/961
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/963
- [ ] https://github.com/deepset-ai/haystack-core-integrations/issues/965
```
