### ISSUE TITLE
Integration for Azure AI Search

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#950]
## Summary and motivation

Motivation from this issue [#6749](https://github.com/deepset-ai/haystack/issues/6749) raised by community members 
## Detailed design

Create a new document store for Azure AI search allowing operations of vector search, hybrid search and keyword search.

## Implementation Breakdown

- [x] Create a document store with CURD operations.
- [x]  Tests for document stores.
- [ ]  Add retrievers.
- [ ] Tests for retrievers.
- [x] Add filters and search operations.
- [ ] Test for filters.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.
```[tasklist]
### Tasks
- [ ] The code is documented with docstrings and was merged in the `main` branch
- [ ] Docs are published at https://docs.haystack.deepset.ai/
- [ ] There is a Github workflow running the tests for the integration nightly and at every PR
- [ ] A label named like `integration:<your integration name>` has been added to this repo
- [ ] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [ ] The package has been released on PyPI
- [ ] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [ ] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [ ] There is an example available to demonstrate the feature
- [ ] The feature was announced through social media
```
